### ISSUE TITLE
Implement all required Milestone 1 features

### ISSUE THREAD

**Issue by nok-ko** [ShakeGuard/2800-202210-BBY06#19]
# Milestone 1
> ⚠️ Big issue, split it off into smaller chunks when working! ⚠️

## Features
- [ ] Implement admin accounts.
- [ ] Make sure accessing profile page w/o being logged in is not allowed.
- **Login Stuff!**
- [ ] Make sure when user logs in, their name/info is displayed in a profile page.
- [ ] Make sure when the user logs in, and is an admin, they are redirected to the admin dashboard.
- **Front-end*
- [ ] Add media queries to all pages.
    - [ ] Use smaller fonts when the layout is narrower.
- [ ] Give feedback to user on incorrect login/signup.

**Comment by nok-ko** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Redirect logged-in users to profile page when they visit `/login`](https://trello.com/c/cuPopOm8/114-redirect-logged-in-users-to-profile-page-when-they-visit-login)

**Comment by nok-ko** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add an admin dashboard](https://trello.com/c/sp2X8crW/113-add-an-admin-dashboard)

**Comment by nok-ko** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make sure all pages have Media Queries!](https://trello.com/c/519nmn9B/115-make-sure-all-pages-have-media-queries)
