### ISSUE TITLE
Put the `console.log`-silencing code behind a feature flag

### ISSUE THREAD

**Issue by nok-ko** [ShakeGuard/2800-202210-BBY06#25]
## Symptoms
- Launching the app with `npm start` outputs cryptic `…`s to the console.
- No clear indication of what is happening
- ???
![image](https://user-images.githubusercontent.com/13428215/167508113-23d6cb31-ad7c-4db4-89c0-f5f503b01443.png)

## TODO
- [ ] Silence `process.stdout.write` in the silenced run mode, too?
    - [ ] Don't silence `console.error`, make sure we never emit `.error`s on normal codepaths
- [ ] Enable `console.*` methods when `--with-log` is passed

**Comment by nok-ko** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [02b/Deploy Node.js app on `shakeguard.nokko.me` (2hr) (2) (?)](https://trello.com/c/EW1A4Bnl/135-02b-deploy-nodejs-app-on-shakeguardnokkome-2hr-2)

**Comment by nok-ko** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make our logging better with a logging library and a command-line argument. (Est. 2hrs) (2) [?]](https://trello.com/c/njRYJn3i/208-make-our-logging-better-with-a-logging-library-and-a-command-line-argument-est-2hrs-2)
